// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: border_radius.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - BorderRadiusRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface BorderRadiusRoot : GPBRootObject
@end

#pragma mark - ImageBorderRadius

typedef GPB_ENUM(ImageBorderRadius_FieldNumber) {
  ImageBorderRadius_FieldNumber_TopLeft = 1,
  ImageBorderRadius_FieldNumber_TopRight = 2,
  ImageBorderRadius_FieldNumber_BottomLeft = 3,
  ImageBorderRadius_FieldNumber_BottomRight = 4,
};

GPB_FINAL @interface ImageBorderRadius : GPBMessage

@property(nonatomic, readwrite) float topLeft;

@property(nonatomic, readwrite) float topRight;

@property(nonatomic, readwrite) float bottomLeft;

@property(nonatomic, readwrite) float bottomRight;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
