// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: enum.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum BoxFit

/** Deliver image scale type between Flutter and native */
typedef GPB_ENUM(BoxFit) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BoxFit_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  BoxFit_Fill = 0,
  BoxFit_Contain = 1,
  BoxFit_Cover = 2,
  BoxFit_FitWidth = 3,
  BoxFit_FitHeight = 4,
  BoxFit_None = 5,
};

GPBEnumDescriptor *BoxFit_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BoxFit_IsValidValue(int32_t value);

#pragma mark - Enum ImageTaskState

/** Describe image task state */
typedef GPB_ENUM(ImageTaskState) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ImageTaskState_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Task has been created but not start yet */
  ImageTaskState_Initialized = 0,
  ImageTaskState_Loading = 1,

  /** Task completed successfully */
  ImageTaskState_Completed = 2,
  ImageTaskState_Canceled = 3,
  ImageTaskState_Failed = 4,
};

GPBEnumDescriptor *ImageTaskState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ImageTaskState_IsValidValue(int32_t value);

#pragma mark - EnumRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface EnumRoot : GPBRootObject
@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
