// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_utils.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class BorderRadius;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum BoxFit

typedef GPB_ENUM(BoxFit) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  BoxFit_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  BoxFit_Fill = 0,
  BoxFit_Contain = 1,
  BoxFit_Cover = 2,
  BoxFit_FitWidth = 3,
  BoxFit_FitHeight = 4,
};

GPBEnumDescriptor *BoxFit_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL BoxFit_IsValidValue(int32_t value);

#pragma mark - Enum TaskState

/** Image task state */
typedef GPB_ENUM(TaskState) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  TaskState_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  /** Task is now ready to start */
  TaskState_Initialized = 0,
  TaskState_Loading = 1,

  /** Task completed successfully */
  TaskState_Completed = 2,
  TaskState_Canceled = 3,
  TaskState_Failed = 4,

  /** For initialization only */
  TaskState_Undefined = 5,
};

GPBEnumDescriptor *TaskState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL TaskState_IsValidValue(int32_t value);

#pragma mark - ImageUtilsRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ImageUtilsRoot : GPBRootObject
@end

#pragma mark - BorderRadius

typedef GPB_ENUM(BorderRadius_FieldNumber) {
  BorderRadius_FieldNumber_TopLeft = 1,
  BorderRadius_FieldNumber_TopRight = 2,
  BorderRadius_FieldNumber_BottomLeft = 3,
  BorderRadius_FieldNumber_BottomRight = 4,
};

GPB_FINAL @interface BorderRadius : GPBMessage

@property(nonatomic, readwrite) double topLeft;

@property(nonatomic, readwrite) double topRight;

@property(nonatomic, readwrite) double bottomLeft;

@property(nonatomic, readwrite) double bottomRight;

@end

#pragma mark - Geometry

typedef GPB_ENUM(Geometry_FieldNumber) {
  Geometry_FieldNumber_Width = 1,
  Geometry_FieldNumber_Height = 2,
  Geometry_FieldNumber_Fit = 3,
  Geometry_FieldNumber_BorderRadius = 4,
};

GPB_FINAL @interface Geometry : GPBMessage

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite) BoxFit fit;

@property(nonatomic, readwrite, strong, null_resettable) BorderRadius *borderRadius;
/** Test to see if @c borderRadius has been set. */
@property(nonatomic, readwrite) BOOL hasBorderRadius;

@end

/**
 * Fetches the raw value of a @c Geometry's @c fit property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t Geometry_Fit_RawValue(Geometry *message);
/**
 * Sets the raw value of an @c Geometry's @c fit property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetGeometry_Fit_RawValue(Geometry *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
