// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_info.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

@class ImageBorderRadius;

NS_ASSUME_NONNULL_BEGIN

#pragma mark - ImageInfoRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface ImageInfoRoot : GPBRootObject
@end

#pragma mark - TextureImageInfo

typedef GPB_ENUM(TextureImageInfo_FieldNumber) {
  TextureImageInfo_FieldNumber_URL = 1,
  TextureImageInfo_FieldNumber_Width = 2,
  TextureImageInfo_FieldNumber_Height = 3,
  TextureImageInfo_FieldNumber_ErrorPlaceholder = 4,
  TextureImageInfo_FieldNumber_Placeholder = 5,
  TextureImageInfo_FieldNumber_BorderRadius = 6,
};

GPB_FINAL @interface TextureImageInfo : GPBMessage

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@property(nonatomic, readwrite) int32_t width;

@property(nonatomic, readwrite) int32_t height;

@property(nonatomic, readwrite, copy, null_resettable) NSString *errorPlaceholder;

@property(nonatomic, readwrite, copy, null_resettable) NSString *placeholder;

@property(nonatomic, readwrite, strong, null_resettable) ImageBorderRadius *borderRadius;
/** Test to see if @c borderRadius has been set. */
@property(nonatomic, readwrite) BOOL hasBorderRadius;

@end

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
