// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: method_call_result.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers_RuntimeSupport.h>
#else
 #import "GPBProtocolBuffers_RuntimeSupport.h"
#endif

#import "MethodCallResult.pbobjc.h"
#import "Enum.pbobjc.h"
// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

#pragma mark - MethodCallResultRoot

@implementation MethodCallResultRoot

// No extensions in the file and none of the imports (direct or indirect)
// defined extensions, so no need to generate +extensionRegistry.

@end

#pragma mark - MethodCallResultRoot_FileDescriptor

static GPBFileDescriptor *MethodCallResultRoot_FileDescriptor(void) {
  // This is called by +initialize so there is no need to worry
  // about thread safety of the singleton.
  static GPBFileDescriptor *descriptor = NULL;
  if (!descriptor) {
    GPB_DEBUG_CHECK_RUNTIME_VERSIONS();
    descriptor = [[GPBFileDescriptor alloc] initWithPackage:@""
                                                     syntax:GPBFileSyntaxProto3];
  }
  return descriptor;
}

#pragma mark - ImageResult

@implementation ImageResult

@dynamic code;
@dynamic textureId;
@dynamic message;
@dynamic URL;
@dynamic state;

typedef struct ImageResult__storage_ {
  uint32_t _has_storage_[1];
  int32_t code;
  ImageTaskState state;
  NSString *message;
  NSString *URL;
  int64_t textureId;
} ImageResult__storage_;

// This method is threadsafe because it is initially called
// in +initialize for each subclass.
+ (GPBDescriptor *)descriptor {
  static GPBDescriptor *descriptor = nil;
  if (!descriptor) {
    static GPBMessageFieldDescription fields[] = {
      {
        .name = "code",
        .dataTypeSpecific.clazz = Nil,
        .number = ImageResult_FieldNumber_Code,
        .hasIndex = 0,
        .offset = (uint32_t)offsetof(ImageResult__storage_, code),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt32,
      },
      {
        .name = "textureId",
        .dataTypeSpecific.clazz = Nil,
        .number = ImageResult_FieldNumber_TextureId,
        .hasIndex = 1,
        .offset = (uint32_t)offsetof(ImageResult__storage_, textureId),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeInt64,
      },
      {
        .name = "message",
        .dataTypeSpecific.clazz = Nil,
        .number = ImageResult_FieldNumber_Message,
        .hasIndex = 2,
        .offset = (uint32_t)offsetof(ImageResult__storage_, message),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "URL",
        .dataTypeSpecific.clazz = Nil,
        .number = ImageResult_FieldNumber_URL,
        .hasIndex = 3,
        .offset = (uint32_t)offsetof(ImageResult__storage_, URL),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldTextFormatNameCustom | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeString,
      },
      {
        .name = "state",
        .dataTypeSpecific.enumDescFunc = ImageTaskState_EnumDescriptor,
        .number = ImageResult_FieldNumber_State,
        .hasIndex = 4,
        .offset = (uint32_t)offsetof(ImageResult__storage_, state),
        .flags = (GPBFieldFlags)(GPBFieldOptional | GPBFieldHasEnumDescriptor | GPBFieldClearHasIvarOnZero),
        .dataType = GPBDataTypeEnum,
      },
    };
    GPBDescriptor *localDescriptor =
        [GPBDescriptor allocDescriptorForClass:[ImageResult class]
                                     rootClass:[MethodCallResultRoot class]
                                          file:MethodCallResultRoot_FileDescriptor()
                                        fields:fields
                                    fieldCount:(uint32_t)(sizeof(fields) / sizeof(GPBMessageFieldDescription))
                                   storageSize:sizeof(ImageResult__storage_)
                                         flags:(GPBDescriptorInitializationFlags)(GPBDescriptorInitializationFlag_UsesClassRefs | GPBDescriptorInitializationFlag_Proto3OptionalKnown)];
#if !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    static const char *extraTextFormatInfo =
        "\002\002\t\000\004!!!\000";
    [localDescriptor setupExtraTextInfo:extraTextFormatInfo];
#endif  // !GPBOBJC_SKIP_MESSAGE_TEXTFORMAT_EXTRAS
    #if defined(DEBUG) && DEBUG
      NSAssert(descriptor == nil, @"Startup recursed!");
    #endif  // DEBUG
    descriptor = localDescriptor;
  }
  return descriptor;
}

@end

int32_t ImageResult_State_RawValue(ImageResult *message) {
  GPBDescriptor *descriptor = [ImageResult descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ImageResult_FieldNumber_State];
  return GPBGetMessageRawEnumField(message, field);
}

void SetImageResult_State_RawValue(ImageResult *message, int32_t value) {
  GPBDescriptor *descriptor = [ImageResult descriptor];
  GPBFieldDescriptor *field = [descriptor fieldWithNumber:ImageResult_FieldNumber_State];
  GPBSetMessageRawEnumField(message, field, value);
}


#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
