// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: method_call_result.proto

// This CPP symbol can be defined to use imports that match up to the framework
// imports needed when using CocoaPods.
#if !defined(GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS)
 #define GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS 0
#endif

#if GPB_USE_PROTOBUF_FRAMEWORK_IMPORTS
 #import <Protobuf/GPBProtocolBuffers.h>
#else
 #import "GPBProtocolBuffers.h"
#endif

#if GOOGLE_PROTOBUF_OBJC_VERSION < 30004
#error This file was generated by a newer version of protoc which is incompatible with your Protocol Buffer library sources.
#endif
#if 30004 < GOOGLE_PROTOBUF_OBJC_MIN_SUPPORTED_VERSION
#error This file was generated by an older version of protoc which is incompatible with your Protocol Buffer library sources.
#endif

// @@protoc_insertion_point(imports)

#pragma clang diagnostic push
#pragma clang diagnostic ignored "-Wdeprecated-declarations"

CF_EXTERN_C_BEGIN

NS_ASSUME_NONNULL_BEGIN

#pragma mark - Enum ImageTaskState

typedef GPB_ENUM(ImageTaskState) {
  /**
   * Value used if any message's field encounters a value that is not defined
   * by this enum. The message will also have C functions to get/set the rawValue
   * of the field.
   **/
  ImageTaskState_GPBUnrecognizedEnumeratorValue = kGPBUnrecognizedEnumeratorValue,
  ImageTaskState_Initialized = 0,
  ImageTaskState_Loading = 1,
  ImageTaskState_Completed = 2,
  ImageTaskState_Canceled = 3,
  ImageTaskState_Failed = 4,
};

GPBEnumDescriptor *ImageTaskState_EnumDescriptor(void);

/**
 * Checks to see if the given value is defined by the enum or was not known at
 * the time this source was generated.
 **/
BOOL ImageTaskState_IsValidValue(int32_t value);

#pragma mark - MethodCallResultRoot

/**
 * Exposes the extension registry for this file.
 *
 * The base class provides:
 * @code
 *   + (GPBExtensionRegistry *)extensionRegistry;
 * @endcode
 * which is a @c GPBExtensionRegistry that includes all the extensions defined by
 * this file and all files that it depends on.
 **/
GPB_FINAL @interface MethodCallResultRoot : GPBRootObject
@end

#pragma mark - ImageResult

typedef GPB_ENUM(ImageResult_FieldNumber) {
  ImageResult_FieldNumber_Code = 1,
  ImageResult_FieldNumber_Message = 2,
  ImageResult_FieldNumber_TextureId = 3,
  ImageResult_FieldNumber_State = 4,
  ImageResult_FieldNumber_URL = 5,
};

GPB_FINAL @interface ImageResult : GPBMessage

@property(nonatomic, readwrite) int32_t code;

@property(nonatomic, readwrite, copy, null_resettable) NSString *message;

@property(nonatomic, readwrite) int32_t textureId;

@property(nonatomic, readwrite) ImageTaskState state;

@property(nonatomic, readwrite, copy, null_resettable) NSString *URL;

@end

/**
 * Fetches the raw value of a @c ImageResult's @c state property, even
 * if the value was not defined by the enum at the time the code was generated.
 **/
int32_t ImageResult_State_RawValue(ImageResult *message);
/**
 * Sets the raw value of an @c ImageResult's @c state property, allowing
 * it to be set to a value that was not defined by the enum at the time the code
 * was generated.
 **/
void SetImageResult_State_RawValue(ImageResult *message, int32_t value);

NS_ASSUME_NONNULL_END

CF_EXTERN_C_END

#pragma clang diagnostic pop

// @@protoc_insertion_point(global_scope)
