/// Plugin API list
///
/// This file is generated by shell script on 2021-08-03, please don't edit this file manually

package com.texture_image.constants

class Methods {
    companion object {
        // Create a new texture image base on a [ImageFetchInfo]
        const val createImageTexture = "createImageTexture"
        
        // Release resource of a texture image once the widget i disposed, param is of [ImageFetchCancelInfo] type
        const val destroyImageTexture = "destroyImageTexture"
        
        // Sets the global config of the plugin, the config detail please refer to [ImageConfigInfo]
        const val textureImageConfig = "textureImageConfig"
        
        // Enable/disable console log, param is a boolean
        const val enableLog = "enableLog"
        
    }
}