/// Plugin API list
///
/// This file is generated by shell script on 2021-09-01, please don't edit this file manually

class Methods {
  /// Create a new texture image base on a [ImageFetchInfo]
  static const createImageTexture = "createImageTexture";
  
  /// Release or cache resource of a texture image once the widget nis disposed, param is of [ImageFetchCancelInfo] type
  static const disposeImageTexture = "disposeImageTexture";
  
  /// Sets the global config of the plugin, the config detail please refer to [ImageConfigInfo]
  static const textureImageConfig = "textureImageConfig";
  
  /// Release all texures waiting in the to-be-reused queue, has no effect on those occupied by Flutter widgets
  static const releaseImageTextureCaches = "releaseImageTextureCaches";
  
  /// Enable/disable console log, param is a boolean
  static const enableLog = "enableLog";
  
}