/// Plugin API list
///
/// This file is generated by shell script on 2021-08-03, please don't edit this file manually

class Methods {
  // Create a new texture image base on a [ImageFetchInfo]
  static const createImageTexture = "createImageTexture";
  
  // Release resource of a texture image once the widget i disposed, param is of [ImageFetchCancelInfo] type
  static const destroyImageTexture = "destroyImageTexture";
  
  // Sets the global config of the plugin, the config detail please refer to [ImageConfigInfo]
  static const textureImageConfig = "textureImageConfig";
  
  // Enable/disable console log, param is a boolean
  static const enableLog = "enableLog";
  
}