// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: border_radius.proto

package com.texture_image.proto;

public final class BorderRadius {
  private BorderRadius() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageBorderRadiusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageBorderRadius)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>float topLeft = 1;</code>
     * @return The topLeft.
     */
    float getTopLeft();

    /**
     * <code>float topRight = 2;</code>
     * @return The topRight.
     */
    float getTopRight();

    /**
     * <code>float bottomLeft = 3;</code>
     * @return The bottomLeft.
     */
    float getBottomLeft();

    /**
     * <code>float bottomRight = 4;</code>
     * @return The bottomRight.
     */
    float getBottomRight();
  }
  /**
   * Protobuf type {@code ImageBorderRadius}
   */
  public static final class ImageBorderRadius extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageBorderRadius)
      ImageBorderRadiusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageBorderRadius.newBuilder() to construct.
    private ImageBorderRadius(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageBorderRadius() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImageBorderRadius();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImageBorderRadius(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 13: {

              topLeft_ = input.readFloat();
              break;
            }
            case 21: {

              topRight_ = input.readFloat();
              break;
            }
            case 29: {

              bottomLeft_ = input.readFloat();
              break;
            }
            case 37: {

              bottomRight_ = input.readFloat();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.texture_image.proto.BorderRadius.internal_static_ImageBorderRadius_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.texture_image.proto.BorderRadius.internal_static_ImageBorderRadius_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.texture_image.proto.BorderRadius.ImageBorderRadius.class, com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder.class);
    }

    public static final int TOPLEFT_FIELD_NUMBER = 1;
    private float topLeft_;
    /**
     * <code>float topLeft = 1;</code>
     * @return The topLeft.
     */
    @java.lang.Override
    public float getTopLeft() {
      return topLeft_;
    }

    public static final int TOPRIGHT_FIELD_NUMBER = 2;
    private float topRight_;
    /**
     * <code>float topRight = 2;</code>
     * @return The topRight.
     */
    @java.lang.Override
    public float getTopRight() {
      return topRight_;
    }

    public static final int BOTTOMLEFT_FIELD_NUMBER = 3;
    private float bottomLeft_;
    /**
     * <code>float bottomLeft = 3;</code>
     * @return The bottomLeft.
     */
    @java.lang.Override
    public float getBottomLeft() {
      return bottomLeft_;
    }

    public static final int BOTTOMRIGHT_FIELD_NUMBER = 4;
    private float bottomRight_;
    /**
     * <code>float bottomRight = 4;</code>
     * @return The bottomRight.
     */
    @java.lang.Override
    public float getBottomRight() {
      return bottomRight_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (topLeft_ != 0F) {
        output.writeFloat(1, topLeft_);
      }
      if (topRight_ != 0F) {
        output.writeFloat(2, topRight_);
      }
      if (bottomLeft_ != 0F) {
        output.writeFloat(3, bottomLeft_);
      }
      if (bottomRight_ != 0F) {
        output.writeFloat(4, bottomRight_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (topLeft_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(1, topLeft_);
      }
      if (topRight_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(2, topRight_);
      }
      if (bottomLeft_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(3, bottomLeft_);
      }
      if (bottomRight_ != 0F) {
        size += com.google.protobuf.CodedOutputStream
          .computeFloatSize(4, bottomRight_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.texture_image.proto.BorderRadius.ImageBorderRadius)) {
        return super.equals(obj);
      }
      com.texture_image.proto.BorderRadius.ImageBorderRadius other = (com.texture_image.proto.BorderRadius.ImageBorderRadius) obj;

      if (java.lang.Float.floatToIntBits(getTopLeft())
          != java.lang.Float.floatToIntBits(
              other.getTopLeft())) return false;
      if (java.lang.Float.floatToIntBits(getTopRight())
          != java.lang.Float.floatToIntBits(
              other.getTopRight())) return false;
      if (java.lang.Float.floatToIntBits(getBottomLeft())
          != java.lang.Float.floatToIntBits(
              other.getBottomLeft())) return false;
      if (java.lang.Float.floatToIntBits(getBottomRight())
          != java.lang.Float.floatToIntBits(
              other.getBottomRight())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPLEFT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTopLeft());
      hash = (37 * hash) + TOPRIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getTopRight());
      hash = (37 * hash) + BOTTOMLEFT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBottomLeft());
      hash = (37 * hash) + BOTTOMRIGHT_FIELD_NUMBER;
      hash = (53 * hash) + java.lang.Float.floatToIntBits(
          getBottomRight());
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.BorderRadius.ImageBorderRadius parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.texture_image.proto.BorderRadius.ImageBorderRadius prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code ImageBorderRadius}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageBorderRadius)
        com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.texture_image.proto.BorderRadius.internal_static_ImageBorderRadius_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.texture_image.proto.BorderRadius.internal_static_ImageBorderRadius_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.texture_image.proto.BorderRadius.ImageBorderRadius.class, com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder.class);
      }

      // Construct using com.texture_image.proto.BorderRadius.ImageBorderRadius.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        topLeft_ = 0F;

        topRight_ = 0F;

        bottomLeft_ = 0F;

        bottomRight_ = 0F;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.texture_image.proto.BorderRadius.internal_static_ImageBorderRadius_descriptor;
      }

      @java.lang.Override
      public com.texture_image.proto.BorderRadius.ImageBorderRadius getDefaultInstanceForType() {
        return com.texture_image.proto.BorderRadius.ImageBorderRadius.getDefaultInstance();
      }

      @java.lang.Override
      public com.texture_image.proto.BorderRadius.ImageBorderRadius build() {
        com.texture_image.proto.BorderRadius.ImageBorderRadius result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.texture_image.proto.BorderRadius.ImageBorderRadius buildPartial() {
        com.texture_image.proto.BorderRadius.ImageBorderRadius result = new com.texture_image.proto.BorderRadius.ImageBorderRadius(this);
        result.topLeft_ = topLeft_;
        result.topRight_ = topRight_;
        result.bottomLeft_ = bottomLeft_;
        result.bottomRight_ = bottomRight_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.texture_image.proto.BorderRadius.ImageBorderRadius) {
          return mergeFrom((com.texture_image.proto.BorderRadius.ImageBorderRadius)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.texture_image.proto.BorderRadius.ImageBorderRadius other) {
        if (other == com.texture_image.proto.BorderRadius.ImageBorderRadius.getDefaultInstance()) return this;
        if (other.getTopLeft() != 0F) {
          setTopLeft(other.getTopLeft());
        }
        if (other.getTopRight() != 0F) {
          setTopRight(other.getTopRight());
        }
        if (other.getBottomLeft() != 0F) {
          setBottomLeft(other.getBottomLeft());
        }
        if (other.getBottomRight() != 0F) {
          setBottomRight(other.getBottomRight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.texture_image.proto.BorderRadius.ImageBorderRadius parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.texture_image.proto.BorderRadius.ImageBorderRadius) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private float topLeft_ ;
      /**
       * <code>float topLeft = 1;</code>
       * @return The topLeft.
       */
      @java.lang.Override
      public float getTopLeft() {
        return topLeft_;
      }
      /**
       * <code>float topLeft = 1;</code>
       * @param value The topLeft to set.
       * @return This builder for chaining.
       */
      public Builder setTopLeft(float value) {
        
        topLeft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float topLeft = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopLeft() {
        
        topLeft_ = 0F;
        onChanged();
        return this;
      }

      private float topRight_ ;
      /**
       * <code>float topRight = 2;</code>
       * @return The topRight.
       */
      @java.lang.Override
      public float getTopRight() {
        return topRight_;
      }
      /**
       * <code>float topRight = 2;</code>
       * @param value The topRight to set.
       * @return This builder for chaining.
       */
      public Builder setTopRight(float value) {
        
        topRight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float topRight = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopRight() {
        
        topRight_ = 0F;
        onChanged();
        return this;
      }

      private float bottomLeft_ ;
      /**
       * <code>float bottomLeft = 3;</code>
       * @return The bottomLeft.
       */
      @java.lang.Override
      public float getBottomLeft() {
        return bottomLeft_;
      }
      /**
       * <code>float bottomLeft = 3;</code>
       * @param value The bottomLeft to set.
       * @return This builder for chaining.
       */
      public Builder setBottomLeft(float value) {
        
        bottomLeft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float bottomLeft = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBottomLeft() {
        
        bottomLeft_ = 0F;
        onChanged();
        return this;
      }

      private float bottomRight_ ;
      /**
       * <code>float bottomRight = 4;</code>
       * @return The bottomRight.
       */
      @java.lang.Override
      public float getBottomRight() {
        return bottomRight_;
      }
      /**
       * <code>float bottomRight = 4;</code>
       * @param value The bottomRight to set.
       * @return This builder for chaining.
       */
      public Builder setBottomRight(float value) {
        
        bottomRight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>float bottomRight = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBottomRight() {
        
        bottomRight_ = 0F;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageBorderRadius)
    }

    // @@protoc_insertion_point(class_scope:ImageBorderRadius)
    private static final com.texture_image.proto.BorderRadius.ImageBorderRadius DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.texture_image.proto.BorderRadius.ImageBorderRadius();
    }

    public static com.texture_image.proto.BorderRadius.ImageBorderRadius getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageBorderRadius>
        PARSER = new com.google.protobuf.AbstractParser<ImageBorderRadius>() {
      @java.lang.Override
      public ImageBorderRadius parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageBorderRadius(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImageBorderRadius> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageBorderRadius> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.texture_image.proto.BorderRadius.ImageBorderRadius getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageBorderRadius_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageBorderRadius_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023border_radius.proto\"_\n\021ImageBorderRadi" +
      "us\022\017\n\007topLeft\030\001 \001(\002\022\020\n\010topRight\030\002 \001(\002\022\022\n" +
      "\nbottomLeft\030\003 \001(\002\022\023\n\013bottomRight\030\004 \001(\002B\031" +
      "\n\027com.texture_image.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_ImageBorderRadius_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageBorderRadius_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageBorderRadius_descriptor,
        new java.lang.String[] { "TopLeft", "TopRight", "BottomLeft", "BottomRight", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
