// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_utils.proto

package com.texture_image.proto;

public final class ImageUtils {
  private ImageUtils() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code BoxFit}
   */
  public enum BoxFit
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>fill = 0;</code>
     */
    fill(0),
    /**
     * <code>contain = 1;</code>
     */
    contain(1),
    /**
     * <code>cover = 2;</code>
     */
    cover(2),
    /**
     * <code>fitWidth = 3;</code>
     */
    fitWidth(3),
    /**
     * <code>fitHeight = 4;</code>
     */
    fitHeight(4),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>fill = 0;</code>
     */
    public static final int fill_VALUE = 0;
    /**
     * <code>contain = 1;</code>
     */
    public static final int contain_VALUE = 1;
    /**
     * <code>cover = 2;</code>
     */
    public static final int cover_VALUE = 2;
    /**
     * <code>fitWidth = 3;</code>
     */
    public static final int fitWidth_VALUE = 3;
    /**
     * <code>fitHeight = 4;</code>
     */
    public static final int fitHeight_VALUE = 4;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static BoxFit valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static BoxFit forNumber(int value) {
      switch (value) {
        case 0: return fill;
        case 1: return contain;
        case 2: return cover;
        case 3: return fitWidth;
        case 4: return fitHeight;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<BoxFit>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        BoxFit> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<BoxFit>() {
            public BoxFit findValueByNumber(int number) {
              return BoxFit.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.texture_image.proto.ImageUtils.getDescriptor().getEnumTypes().get(0);
    }

    private static final BoxFit[] VALUES = values();

    public static BoxFit valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private BoxFit(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:BoxFit)
  }

  /**
   * <pre>
   * Image task state
   * </pre>
   *
   * Protobuf enum {@code TaskState}
   */
  public enum TaskState
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <pre>
     * Task is now ready to start
     * </pre>
     *
     * <code>initialized = 0;</code>
     */
    initialized(0),
    /**
     * <code>loading = 1;</code>
     */
    loading(1),
    /**
     * <pre>
     * Task completed successfully
     * </pre>
     *
     * <code>completed = 2;</code>
     */
    completed(2),
    /**
     * <code>failed = 3;</code>
     */
    failed(3),
    /**
     * <pre>
     * Image widget has been disposed
     * </pre>
     *
     * <code>disposed = 4;</code>
     */
    disposed(4),
    /**
     * <pre>
     * For initialization only
     * </pre>
     *
     * <code>undefined = 5;</code>
     */
    undefined(5),
    /**
     * <pre>
     * Watiing for reusing
     * </pre>
     *
     * <code>prepreReuse = 6;</code>
     */
    prepreReuse(6),
    UNRECOGNIZED(-1),
    ;

    /**
     * <pre>
     * Task is now ready to start
     * </pre>
     *
     * <code>initialized = 0;</code>
     */
    public static final int initialized_VALUE = 0;
    /**
     * <code>loading = 1;</code>
     */
    public static final int loading_VALUE = 1;
    /**
     * <pre>
     * Task completed successfully
     * </pre>
     *
     * <code>completed = 2;</code>
     */
    public static final int completed_VALUE = 2;
    /**
     * <code>failed = 3;</code>
     */
    public static final int failed_VALUE = 3;
    /**
     * <pre>
     * Image widget has been disposed
     * </pre>
     *
     * <code>disposed = 4;</code>
     */
    public static final int disposed_VALUE = 4;
    /**
     * <pre>
     * For initialization only
     * </pre>
     *
     * <code>undefined = 5;</code>
     */
    public static final int undefined_VALUE = 5;
    /**
     * <pre>
     * Watiing for reusing
     * </pre>
     *
     * <code>prepreReuse = 6;</code>
     */
    public static final int prepreReuse_VALUE = 6;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static TaskState valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static TaskState forNumber(int value) {
      switch (value) {
        case 0: return initialized;
        case 1: return loading;
        case 2: return completed;
        case 3: return failed;
        case 4: return disposed;
        case 5: return undefined;
        case 6: return prepreReuse;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<TaskState>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        TaskState> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<TaskState>() {
            public TaskState findValueByNumber(int number) {
              return TaskState.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return com.texture_image.proto.ImageUtils.getDescriptor().getEnumTypes().get(1);
    }

    private static final TaskState[] VALUES = values();

    public static TaskState valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private TaskState(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:TaskState)
  }

  public interface BorderRadiusOrBuilder extends
      // @@protoc_insertion_point(interface_extends:BorderRadius)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>double topLeft = 1;</code>
     * @return The topLeft.
     */
    double getTopLeft();

    /**
     * <code>double topRight = 2;</code>
     * @return The topRight.
     */
    double getTopRight();

    /**
     * <code>double bottomLeft = 3;</code>
     * @return The bottomLeft.
     */
    double getBottomLeft();

    /**
     * <code>double bottomRight = 4;</code>
     * @return The bottomRight.
     */
    double getBottomRight();
  }
  /**
   * Protobuf type {@code BorderRadius}
   */
  public static final class BorderRadius extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:BorderRadius)
      BorderRadiusOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use BorderRadius.newBuilder() to construct.
    private BorderRadius(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private BorderRadius() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new BorderRadius();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private BorderRadius(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 9: {

              topLeft_ = input.readDouble();
              break;
            }
            case 17: {

              topRight_ = input.readDouble();
              break;
            }
            case 25: {

              bottomLeft_ = input.readDouble();
              break;
            }
            case 33: {

              bottomRight_ = input.readDouble();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.texture_image.proto.ImageUtils.internal_static_BorderRadius_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.texture_image.proto.ImageUtils.internal_static_BorderRadius_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.texture_image.proto.ImageUtils.BorderRadius.class, com.texture_image.proto.ImageUtils.BorderRadius.Builder.class);
    }

    public static final int TOPLEFT_FIELD_NUMBER = 1;
    private double topLeft_;
    /**
     * <code>double topLeft = 1;</code>
     * @return The topLeft.
     */
    @java.lang.Override
    public double getTopLeft() {
      return topLeft_;
    }

    public static final int TOPRIGHT_FIELD_NUMBER = 2;
    private double topRight_;
    /**
     * <code>double topRight = 2;</code>
     * @return The topRight.
     */
    @java.lang.Override
    public double getTopRight() {
      return topRight_;
    }

    public static final int BOTTOMLEFT_FIELD_NUMBER = 3;
    private double bottomLeft_;
    /**
     * <code>double bottomLeft = 3;</code>
     * @return The bottomLeft.
     */
    @java.lang.Override
    public double getBottomLeft() {
      return bottomLeft_;
    }

    public static final int BOTTOMRIGHT_FIELD_NUMBER = 4;
    private double bottomRight_;
    /**
     * <code>double bottomRight = 4;</code>
     * @return The bottomRight.
     */
    @java.lang.Override
    public double getBottomRight() {
      return bottomRight_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (topLeft_ != 0D) {
        output.writeDouble(1, topLeft_);
      }
      if (topRight_ != 0D) {
        output.writeDouble(2, topRight_);
      }
      if (bottomLeft_ != 0D) {
        output.writeDouble(3, bottomLeft_);
      }
      if (bottomRight_ != 0D) {
        output.writeDouble(4, bottomRight_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (topLeft_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(1, topLeft_);
      }
      if (topRight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(2, topRight_);
      }
      if (bottomLeft_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(3, bottomLeft_);
      }
      if (bottomRight_ != 0D) {
        size += com.google.protobuf.CodedOutputStream
          .computeDoubleSize(4, bottomRight_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.texture_image.proto.ImageUtils.BorderRadius)) {
        return super.equals(obj);
      }
      com.texture_image.proto.ImageUtils.BorderRadius other = (com.texture_image.proto.ImageUtils.BorderRadius) obj;

      if (java.lang.Double.doubleToLongBits(getTopLeft())
          != java.lang.Double.doubleToLongBits(
              other.getTopLeft())) return false;
      if (java.lang.Double.doubleToLongBits(getTopRight())
          != java.lang.Double.doubleToLongBits(
              other.getTopRight())) return false;
      if (java.lang.Double.doubleToLongBits(getBottomLeft())
          != java.lang.Double.doubleToLongBits(
              other.getBottomLeft())) return false;
      if (java.lang.Double.doubleToLongBits(getBottomRight())
          != java.lang.Double.doubleToLongBits(
              other.getBottomRight())) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + TOPLEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTopLeft()));
      hash = (37 * hash) + TOPRIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getTopRight()));
      hash = (37 * hash) + BOTTOMLEFT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBottomLeft()));
      hash = (37 * hash) + BOTTOMRIGHT_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          java.lang.Double.doubleToLongBits(getBottomRight()));
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.BorderRadius parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.texture_image.proto.ImageUtils.BorderRadius prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code BorderRadius}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:BorderRadius)
        com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.texture_image.proto.ImageUtils.internal_static_BorderRadius_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.texture_image.proto.ImageUtils.internal_static_BorderRadius_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.texture_image.proto.ImageUtils.BorderRadius.class, com.texture_image.proto.ImageUtils.BorderRadius.Builder.class);
      }

      // Construct using com.texture_image.proto.ImageUtils.BorderRadius.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        topLeft_ = 0D;

        topRight_ = 0D;

        bottomLeft_ = 0D;

        bottomRight_ = 0D;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.texture_image.proto.ImageUtils.internal_static_BorderRadius_descriptor;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.BorderRadius getDefaultInstanceForType() {
        return com.texture_image.proto.ImageUtils.BorderRadius.getDefaultInstance();
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.BorderRadius build() {
        com.texture_image.proto.ImageUtils.BorderRadius result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.BorderRadius buildPartial() {
        com.texture_image.proto.ImageUtils.BorderRadius result = new com.texture_image.proto.ImageUtils.BorderRadius(this);
        result.topLeft_ = topLeft_;
        result.topRight_ = topRight_;
        result.bottomLeft_ = bottomLeft_;
        result.bottomRight_ = bottomRight_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.texture_image.proto.ImageUtils.BorderRadius) {
          return mergeFrom((com.texture_image.proto.ImageUtils.BorderRadius)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.texture_image.proto.ImageUtils.BorderRadius other) {
        if (other == com.texture_image.proto.ImageUtils.BorderRadius.getDefaultInstance()) return this;
        if (other.getTopLeft() != 0D) {
          setTopLeft(other.getTopLeft());
        }
        if (other.getTopRight() != 0D) {
          setTopRight(other.getTopRight());
        }
        if (other.getBottomLeft() != 0D) {
          setBottomLeft(other.getBottomLeft());
        }
        if (other.getBottomRight() != 0D) {
          setBottomRight(other.getBottomRight());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.texture_image.proto.ImageUtils.BorderRadius parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.texture_image.proto.ImageUtils.BorderRadius) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private double topLeft_ ;
      /**
       * <code>double topLeft = 1;</code>
       * @return The topLeft.
       */
      @java.lang.Override
      public double getTopLeft() {
        return topLeft_;
      }
      /**
       * <code>double topLeft = 1;</code>
       * @param value The topLeft to set.
       * @return This builder for chaining.
       */
      public Builder setTopLeft(double value) {
        
        topLeft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double topLeft = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopLeft() {
        
        topLeft_ = 0D;
        onChanged();
        return this;
      }

      private double topRight_ ;
      /**
       * <code>double topRight = 2;</code>
       * @return The topRight.
       */
      @java.lang.Override
      public double getTopRight() {
        return topRight_;
      }
      /**
       * <code>double topRight = 2;</code>
       * @param value The topRight to set.
       * @return This builder for chaining.
       */
      public Builder setTopRight(double value) {
        
        topRight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double topRight = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTopRight() {
        
        topRight_ = 0D;
        onChanged();
        return this;
      }

      private double bottomLeft_ ;
      /**
       * <code>double bottomLeft = 3;</code>
       * @return The bottomLeft.
       */
      @java.lang.Override
      public double getBottomLeft() {
        return bottomLeft_;
      }
      /**
       * <code>double bottomLeft = 3;</code>
       * @param value The bottomLeft to set.
       * @return This builder for chaining.
       */
      public Builder setBottomLeft(double value) {
        
        bottomLeft_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double bottomLeft = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearBottomLeft() {
        
        bottomLeft_ = 0D;
        onChanged();
        return this;
      }

      private double bottomRight_ ;
      /**
       * <code>double bottomRight = 4;</code>
       * @return The bottomRight.
       */
      @java.lang.Override
      public double getBottomRight() {
        return bottomRight_;
      }
      /**
       * <code>double bottomRight = 4;</code>
       * @param value The bottomRight to set.
       * @return This builder for chaining.
       */
      public Builder setBottomRight(double value) {
        
        bottomRight_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>double bottomRight = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearBottomRight() {
        
        bottomRight_ = 0D;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:BorderRadius)
    }

    // @@protoc_insertion_point(class_scope:BorderRadius)
    private static final com.texture_image.proto.ImageUtils.BorderRadius DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.texture_image.proto.ImageUtils.BorderRadius();
    }

    public static com.texture_image.proto.ImageUtils.BorderRadius getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<BorderRadius>
        PARSER = new com.google.protobuf.AbstractParser<BorderRadius>() {
      @java.lang.Override
      public BorderRadius parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new BorderRadius(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<BorderRadius> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<BorderRadius> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.texture_image.proto.ImageUtils.BorderRadius getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface GeometryOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Geometry)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <pre>
     * Indicate whether this image has alpha channel
     * On Android platform, if this is not supported,
     * then the bitmap loader will use RGB_565 format
     * to decode the image, result in reducing half
     * size. Otherwise, ARGB_888 format will used,
     * on this format, each pixel is stored on 4 bytes.
     * It is suggested to disable this feature as if
     * it's possible anyway.
     * </pre>
     *
     * <code>bool supportAlpha = 3;</code>
     * @return The supportAlpha.
     */
    boolean getSupportAlpha();

    /**
     * <code>.BoxFit fit = 4;</code>
     * @return The enum numeric value on the wire for fit.
     */
    int getFitValue();
    /**
     * <code>.BoxFit fit = 4;</code>
     * @return The fit.
     */
    com.texture_image.proto.ImageUtils.BoxFit getFit();

    /**
     * <code>.BorderRadius borderRadius = 5;</code>
     * @return Whether the borderRadius field is set.
     */
    boolean hasBorderRadius();
    /**
     * <code>.BorderRadius borderRadius = 5;</code>
     * @return The borderRadius.
     */
    com.texture_image.proto.ImageUtils.BorderRadius getBorderRadius();
    /**
     * <code>.BorderRadius borderRadius = 5;</code>
     */
    com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder getBorderRadiusOrBuilder();
  }
  /**
   * Protobuf type {@code Geometry}
   */
  public static final class Geometry extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Geometry)
      GeometryOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Geometry.newBuilder() to construct.
    private Geometry(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Geometry() {
      fit_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Geometry();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Geometry(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              width_ = input.readInt32();
              break;
            }
            case 16: {

              height_ = input.readInt32();
              break;
            }
            case 24: {

              supportAlpha_ = input.readBool();
              break;
            }
            case 32: {
              int rawValue = input.readEnum();

              fit_ = rawValue;
              break;
            }
            case 42: {
              com.texture_image.proto.ImageUtils.BorderRadius.Builder subBuilder = null;
              if (borderRadius_ != null) {
                subBuilder = borderRadius_.toBuilder();
              }
              borderRadius_ = input.readMessage(com.texture_image.proto.ImageUtils.BorderRadius.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(borderRadius_);
                borderRadius_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.texture_image.proto.ImageUtils.internal_static_Geometry_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.texture_image.proto.ImageUtils.internal_static_Geometry_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.texture_image.proto.ImageUtils.Geometry.class, com.texture_image.proto.ImageUtils.Geometry.Builder.class);
    }

    public static final int WIDTH_FIELD_NUMBER = 1;
    private int width_;
    /**
     * <code>int32 width = 1;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 2;
    private int height_;
    /**
     * <code>int32 height = 2;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int SUPPORTALPHA_FIELD_NUMBER = 3;
    private boolean supportAlpha_;
    /**
     * <pre>
     * Indicate whether this image has alpha channel
     * On Android platform, if this is not supported,
     * then the bitmap loader will use RGB_565 format
     * to decode the image, result in reducing half
     * size. Otherwise, ARGB_888 format will used,
     * on this format, each pixel is stored on 4 bytes.
     * It is suggested to disable this feature as if
     * it's possible anyway.
     * </pre>
     *
     * <code>bool supportAlpha = 3;</code>
     * @return The supportAlpha.
     */
    @java.lang.Override
    public boolean getSupportAlpha() {
      return supportAlpha_;
    }

    public static final int FIT_FIELD_NUMBER = 4;
    private int fit_;
    /**
     * <code>.BoxFit fit = 4;</code>
     * @return The enum numeric value on the wire for fit.
     */
    @java.lang.Override public int getFitValue() {
      return fit_;
    }
    /**
     * <code>.BoxFit fit = 4;</code>
     * @return The fit.
     */
    @java.lang.Override public com.texture_image.proto.ImageUtils.BoxFit getFit() {
      @SuppressWarnings("deprecation")
      com.texture_image.proto.ImageUtils.BoxFit result = com.texture_image.proto.ImageUtils.BoxFit.valueOf(fit_);
      return result == null ? com.texture_image.proto.ImageUtils.BoxFit.UNRECOGNIZED : result;
    }

    public static final int BORDERRADIUS_FIELD_NUMBER = 5;
    private com.texture_image.proto.ImageUtils.BorderRadius borderRadius_;
    /**
     * <code>.BorderRadius borderRadius = 5;</code>
     * @return Whether the borderRadius field is set.
     */
    @java.lang.Override
    public boolean hasBorderRadius() {
      return borderRadius_ != null;
    }
    /**
     * <code>.BorderRadius borderRadius = 5;</code>
     * @return The borderRadius.
     */
    @java.lang.Override
    public com.texture_image.proto.ImageUtils.BorderRadius getBorderRadius() {
      return borderRadius_ == null ? com.texture_image.proto.ImageUtils.BorderRadius.getDefaultInstance() : borderRadius_;
    }
    /**
     * <code>.BorderRadius borderRadius = 5;</code>
     */
    @java.lang.Override
    public com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder getBorderRadiusOrBuilder() {
      return getBorderRadius();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (width_ != 0) {
        output.writeInt32(1, width_);
      }
      if (height_ != 0) {
        output.writeInt32(2, height_);
      }
      if (supportAlpha_ != false) {
        output.writeBool(3, supportAlpha_);
      }
      if (fit_ != com.texture_image.proto.ImageUtils.BoxFit.fill.getNumber()) {
        output.writeEnum(4, fit_);
      }
      if (borderRadius_ != null) {
        output.writeMessage(5, getBorderRadius());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, height_);
      }
      if (supportAlpha_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(3, supportAlpha_);
      }
      if (fit_ != com.texture_image.proto.ImageUtils.BoxFit.fill.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(4, fit_);
      }
      if (borderRadius_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getBorderRadius());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.texture_image.proto.ImageUtils.Geometry)) {
        return super.equals(obj);
      }
      com.texture_image.proto.ImageUtils.Geometry other = (com.texture_image.proto.ImageUtils.Geometry) obj;

      if (getWidth()
          != other.getWidth()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (getSupportAlpha()
          != other.getSupportAlpha()) return false;
      if (fit_ != other.fit_) return false;
      if (hasBorderRadius() != other.hasBorderRadius()) return false;
      if (hasBorderRadius()) {
        if (!getBorderRadius()
            .equals(other.getBorderRadius())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + SUPPORTALPHA_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getSupportAlpha());
      hash = (37 * hash) + FIT_FIELD_NUMBER;
      hash = (53 * hash) + fit_;
      if (hasBorderRadius()) {
        hash = (37 * hash) + BORDERRADIUS_FIELD_NUMBER;
        hash = (53 * hash) + getBorderRadius().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.Geometry parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.texture_image.proto.ImageUtils.Geometry prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code Geometry}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Geometry)
        com.texture_image.proto.ImageUtils.GeometryOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.texture_image.proto.ImageUtils.internal_static_Geometry_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.texture_image.proto.ImageUtils.internal_static_Geometry_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.texture_image.proto.ImageUtils.Geometry.class, com.texture_image.proto.ImageUtils.Geometry.Builder.class);
      }

      // Construct using com.texture_image.proto.ImageUtils.Geometry.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        width_ = 0;

        height_ = 0;

        supportAlpha_ = false;

        fit_ = 0;

        if (borderRadiusBuilder_ == null) {
          borderRadius_ = null;
        } else {
          borderRadius_ = null;
          borderRadiusBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.texture_image.proto.ImageUtils.internal_static_Geometry_descriptor;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.Geometry getDefaultInstanceForType() {
        return com.texture_image.proto.ImageUtils.Geometry.getDefaultInstance();
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.Geometry build() {
        com.texture_image.proto.ImageUtils.Geometry result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.Geometry buildPartial() {
        com.texture_image.proto.ImageUtils.Geometry result = new com.texture_image.proto.ImageUtils.Geometry(this);
        result.width_ = width_;
        result.height_ = height_;
        result.supportAlpha_ = supportAlpha_;
        result.fit_ = fit_;
        if (borderRadiusBuilder_ == null) {
          result.borderRadius_ = borderRadius_;
        } else {
          result.borderRadius_ = borderRadiusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.texture_image.proto.ImageUtils.Geometry) {
          return mergeFrom((com.texture_image.proto.ImageUtils.Geometry)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.texture_image.proto.ImageUtils.Geometry other) {
        if (other == com.texture_image.proto.ImageUtils.Geometry.getDefaultInstance()) return this;
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (other.getSupportAlpha() != false) {
          setSupportAlpha(other.getSupportAlpha());
        }
        if (other.fit_ != 0) {
          setFitValue(other.getFitValue());
        }
        if (other.hasBorderRadius()) {
          mergeBorderRadius(other.getBorderRadius());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.texture_image.proto.ImageUtils.Geometry parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.texture_image.proto.ImageUtils.Geometry) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 1;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 1;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 2;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 2;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private boolean supportAlpha_ ;
      /**
       * <pre>
       * Indicate whether this image has alpha channel
       * On Android platform, if this is not supported,
       * then the bitmap loader will use RGB_565 format
       * to decode the image, result in reducing half
       * size. Otherwise, ARGB_888 format will used,
       * on this format, each pixel is stored on 4 bytes.
       * It is suggested to disable this feature as if
       * it's possible anyway.
       * </pre>
       *
       * <code>bool supportAlpha = 3;</code>
       * @return The supportAlpha.
       */
      @java.lang.Override
      public boolean getSupportAlpha() {
        return supportAlpha_;
      }
      /**
       * <pre>
       * Indicate whether this image has alpha channel
       * On Android platform, if this is not supported,
       * then the bitmap loader will use RGB_565 format
       * to decode the image, result in reducing half
       * size. Otherwise, ARGB_888 format will used,
       * on this format, each pixel is stored on 4 bytes.
       * It is suggested to disable this feature as if
       * it's possible anyway.
       * </pre>
       *
       * <code>bool supportAlpha = 3;</code>
       * @param value The supportAlpha to set.
       * @return This builder for chaining.
       */
      public Builder setSupportAlpha(boolean value) {
        
        supportAlpha_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Indicate whether this image has alpha channel
       * On Android platform, if this is not supported,
       * then the bitmap loader will use RGB_565 format
       * to decode the image, result in reducing half
       * size. Otherwise, ARGB_888 format will used,
       * on this format, each pixel is stored on 4 bytes.
       * It is suggested to disable this feature as if
       * it's possible anyway.
       * </pre>
       *
       * <code>bool supportAlpha = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearSupportAlpha() {
        
        supportAlpha_ = false;
        onChanged();
        return this;
      }

      private int fit_ = 0;
      /**
       * <code>.BoxFit fit = 4;</code>
       * @return The enum numeric value on the wire for fit.
       */
      @java.lang.Override public int getFitValue() {
        return fit_;
      }
      /**
       * <code>.BoxFit fit = 4;</code>
       * @param value The enum numeric value on the wire for fit to set.
       * @return This builder for chaining.
       */
      public Builder setFitValue(int value) {
        
        fit_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.BoxFit fit = 4;</code>
       * @return The fit.
       */
      @java.lang.Override
      public com.texture_image.proto.ImageUtils.BoxFit getFit() {
        @SuppressWarnings("deprecation")
        com.texture_image.proto.ImageUtils.BoxFit result = com.texture_image.proto.ImageUtils.BoxFit.valueOf(fit_);
        return result == null ? com.texture_image.proto.ImageUtils.BoxFit.UNRECOGNIZED : result;
      }
      /**
       * <code>.BoxFit fit = 4;</code>
       * @param value The fit to set.
       * @return This builder for chaining.
       */
      public Builder setFit(com.texture_image.proto.ImageUtils.BoxFit value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        fit_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.BoxFit fit = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearFit() {
        
        fit_ = 0;
        onChanged();
        return this;
      }

      private com.texture_image.proto.ImageUtils.BorderRadius borderRadius_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.texture_image.proto.ImageUtils.BorderRadius, com.texture_image.proto.ImageUtils.BorderRadius.Builder, com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder> borderRadiusBuilder_;
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       * @return Whether the borderRadius field is set.
       */
      public boolean hasBorderRadius() {
        return borderRadiusBuilder_ != null || borderRadius_ != null;
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       * @return The borderRadius.
       */
      public com.texture_image.proto.ImageUtils.BorderRadius getBorderRadius() {
        if (borderRadiusBuilder_ == null) {
          return borderRadius_ == null ? com.texture_image.proto.ImageUtils.BorderRadius.getDefaultInstance() : borderRadius_;
        } else {
          return borderRadiusBuilder_.getMessage();
        }
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      public Builder setBorderRadius(com.texture_image.proto.ImageUtils.BorderRadius value) {
        if (borderRadiusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          borderRadius_ = value;
          onChanged();
        } else {
          borderRadiusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      public Builder setBorderRadius(
          com.texture_image.proto.ImageUtils.BorderRadius.Builder builderForValue) {
        if (borderRadiusBuilder_ == null) {
          borderRadius_ = builderForValue.build();
          onChanged();
        } else {
          borderRadiusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      public Builder mergeBorderRadius(com.texture_image.proto.ImageUtils.BorderRadius value) {
        if (borderRadiusBuilder_ == null) {
          if (borderRadius_ != null) {
            borderRadius_ =
              com.texture_image.proto.ImageUtils.BorderRadius.newBuilder(borderRadius_).mergeFrom(value).buildPartial();
          } else {
            borderRadius_ = value;
          }
          onChanged();
        } else {
          borderRadiusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      public Builder clearBorderRadius() {
        if (borderRadiusBuilder_ == null) {
          borderRadius_ = null;
          onChanged();
        } else {
          borderRadius_ = null;
          borderRadiusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      public com.texture_image.proto.ImageUtils.BorderRadius.Builder getBorderRadiusBuilder() {
        
        onChanged();
        return getBorderRadiusFieldBuilder().getBuilder();
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      public com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder getBorderRadiusOrBuilder() {
        if (borderRadiusBuilder_ != null) {
          return borderRadiusBuilder_.getMessageOrBuilder();
        } else {
          return borderRadius_ == null ?
              com.texture_image.proto.ImageUtils.BorderRadius.getDefaultInstance() : borderRadius_;
        }
      }
      /**
       * <code>.BorderRadius borderRadius = 5;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.texture_image.proto.ImageUtils.BorderRadius, com.texture_image.proto.ImageUtils.BorderRadius.Builder, com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder> 
          getBorderRadiusFieldBuilder() {
        if (borderRadiusBuilder_ == null) {
          borderRadiusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.texture_image.proto.ImageUtils.BorderRadius, com.texture_image.proto.ImageUtils.BorderRadius.Builder, com.texture_image.proto.ImageUtils.BorderRadiusOrBuilder>(
                  getBorderRadius(),
                  getParentForChildren(),
                  isClean());
          borderRadius_ = null;
        }
        return borderRadiusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Geometry)
    }

    // @@protoc_insertion_point(class_scope:Geometry)
    private static final com.texture_image.proto.ImageUtils.Geometry DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.texture_image.proto.ImageUtils.Geometry();
    }

    public static com.texture_image.proto.ImageUtils.Geometry getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Geometry>
        PARSER = new com.google.protobuf.AbstractParser<Geometry>() {
      @java.lang.Override
      public Geometry parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Geometry(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Geometry> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Geometry> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.texture_image.proto.ImageUtils.Geometry getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface QualityOrBuilder extends
      // @@protoc_insertion_point(interface_extends:Quality)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * Allow the plugin the recalculate the image size along with
     * target device's density DPI, this logic is in utils/GeometryUtil.kt
     * This will result in resampling of the image and it's kind of
     * lossy compression, but it is not as obvious as setting [quality]
     * to this Quality object.
     * If this is not allowed, than images will rendered using the best
     * quality, thus more memory space is taken. It's suggested to open
     * this setting
     * </pre>
     *
     * <code>bool autoDownscale = 1;</code>
     * @return The autoDownscale.
     */
    boolean getAutoDownscale();

    /**
     * <pre>
     * If one of the image dimensions' value is lower than this value,
     * it will not downscale automatically although [autoDownscale] is
     * enabled to guarantee no over-reduced image quality. The this value
     * is not allow smaller than 80
     * </pre>
     *
     * <code>int32 minimumAutoDownscaleTriggerSize = 2;</code>
     * @return The minimumAutoDownscaleTriggerSize.
     */
    int getMinimumAutoDownscaleTriggerSize();

    /**
     * <pre>
     * Image compression quality, assgining this value will trigger
     * compression logic of target bitmap, and it's lossy compression
     * if the target bitmap is not in PNG format. Comporess will
     * cost CPU time to save memory space, it's not suggested to do
     * compression if there's no memory pressure
     * </pre>
     *
     * <code>int32 quality = 3;</code>
     * @return The quality.
     */
    int getQuality();
  }
  /**
   * <pre>
   * Contains custom configs about setting image quality
   * </pre>
   *
   * Protobuf type {@code Quality}
   */
  public static final class Quality extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:Quality)
      QualityOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use Quality.newBuilder() to construct.
    private Quality(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private Quality() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new Quality();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private Quality(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              autoDownscale_ = input.readBool();
              break;
            }
            case 16: {

              minimumAutoDownscaleTriggerSize_ = input.readInt32();
              break;
            }
            case 24: {

              quality_ = input.readInt32();
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.texture_image.proto.ImageUtils.internal_static_Quality_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.texture_image.proto.ImageUtils.internal_static_Quality_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.texture_image.proto.ImageUtils.Quality.class, com.texture_image.proto.ImageUtils.Quality.Builder.class);
    }

    public static final int AUTODOWNSCALE_FIELD_NUMBER = 1;
    private boolean autoDownscale_;
    /**
     * <pre>
     * Allow the plugin the recalculate the image size along with
     * target device's density DPI, this logic is in utils/GeometryUtil.kt
     * This will result in resampling of the image and it's kind of
     * lossy compression, but it is not as obvious as setting [quality]
     * to this Quality object.
     * If this is not allowed, than images will rendered using the best
     * quality, thus more memory space is taken. It's suggested to open
     * this setting
     * </pre>
     *
     * <code>bool autoDownscale = 1;</code>
     * @return The autoDownscale.
     */
    @java.lang.Override
    public boolean getAutoDownscale() {
      return autoDownscale_;
    }

    public static final int MINIMUMAUTODOWNSCALETRIGGERSIZE_FIELD_NUMBER = 2;
    private int minimumAutoDownscaleTriggerSize_;
    /**
     * <pre>
     * If one of the image dimensions' value is lower than this value,
     * it will not downscale automatically although [autoDownscale] is
     * enabled to guarantee no over-reduced image quality. The this value
     * is not allow smaller than 80
     * </pre>
     *
     * <code>int32 minimumAutoDownscaleTriggerSize = 2;</code>
     * @return The minimumAutoDownscaleTriggerSize.
     */
    @java.lang.Override
    public int getMinimumAutoDownscaleTriggerSize() {
      return minimumAutoDownscaleTriggerSize_;
    }

    public static final int QUALITY_FIELD_NUMBER = 3;
    private int quality_;
    /**
     * <pre>
     * Image compression quality, assgining this value will trigger
     * compression logic of target bitmap, and it's lossy compression
     * if the target bitmap is not in PNG format. Comporess will
     * cost CPU time to save memory space, it's not suggested to do
     * compression if there's no memory pressure
     * </pre>
     *
     * <code>int32 quality = 3;</code>
     * @return The quality.
     */
    @java.lang.Override
    public int getQuality() {
      return quality_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (autoDownscale_ != false) {
        output.writeBool(1, autoDownscale_);
      }
      if (minimumAutoDownscaleTriggerSize_ != 0) {
        output.writeInt32(2, minimumAutoDownscaleTriggerSize_);
      }
      if (quality_ != 0) {
        output.writeInt32(3, quality_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (autoDownscale_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, autoDownscale_);
      }
      if (minimumAutoDownscaleTriggerSize_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, minimumAutoDownscaleTriggerSize_);
      }
      if (quality_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, quality_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.texture_image.proto.ImageUtils.Quality)) {
        return super.equals(obj);
      }
      com.texture_image.proto.ImageUtils.Quality other = (com.texture_image.proto.ImageUtils.Quality) obj;

      if (getAutoDownscale()
          != other.getAutoDownscale()) return false;
      if (getMinimumAutoDownscaleTriggerSize()
          != other.getMinimumAutoDownscaleTriggerSize()) return false;
      if (getQuality()
          != other.getQuality()) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + AUTODOWNSCALE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getAutoDownscale());
      hash = (37 * hash) + MINIMUMAUTODOWNSCALETRIGGERSIZE_FIELD_NUMBER;
      hash = (53 * hash) + getMinimumAutoDownscaleTriggerSize();
      hash = (37 * hash) + QUALITY_FIELD_NUMBER;
      hash = (53 * hash) + getQuality();
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageUtils.Quality parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.texture_image.proto.ImageUtils.Quality prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * Contains custom configs about setting image quality
     * </pre>
     *
     * Protobuf type {@code Quality}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:Quality)
        com.texture_image.proto.ImageUtils.QualityOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.texture_image.proto.ImageUtils.internal_static_Quality_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.texture_image.proto.ImageUtils.internal_static_Quality_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.texture_image.proto.ImageUtils.Quality.class, com.texture_image.proto.ImageUtils.Quality.Builder.class);
      }

      // Construct using com.texture_image.proto.ImageUtils.Quality.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        autoDownscale_ = false;

        minimumAutoDownscaleTriggerSize_ = 0;

        quality_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.texture_image.proto.ImageUtils.internal_static_Quality_descriptor;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.Quality getDefaultInstanceForType() {
        return com.texture_image.proto.ImageUtils.Quality.getDefaultInstance();
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.Quality build() {
        com.texture_image.proto.ImageUtils.Quality result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageUtils.Quality buildPartial() {
        com.texture_image.proto.ImageUtils.Quality result = new com.texture_image.proto.ImageUtils.Quality(this);
        result.autoDownscale_ = autoDownscale_;
        result.minimumAutoDownscaleTriggerSize_ = minimumAutoDownscaleTriggerSize_;
        result.quality_ = quality_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.texture_image.proto.ImageUtils.Quality) {
          return mergeFrom((com.texture_image.proto.ImageUtils.Quality)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.texture_image.proto.ImageUtils.Quality other) {
        if (other == com.texture_image.proto.ImageUtils.Quality.getDefaultInstance()) return this;
        if (other.getAutoDownscale() != false) {
          setAutoDownscale(other.getAutoDownscale());
        }
        if (other.getMinimumAutoDownscaleTriggerSize() != 0) {
          setMinimumAutoDownscaleTriggerSize(other.getMinimumAutoDownscaleTriggerSize());
        }
        if (other.getQuality() != 0) {
          setQuality(other.getQuality());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.texture_image.proto.ImageUtils.Quality parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.texture_image.proto.ImageUtils.Quality) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private boolean autoDownscale_ ;
      /**
       * <pre>
       * Allow the plugin the recalculate the image size along with
       * target device's density DPI, this logic is in utils/GeometryUtil.kt
       * This will result in resampling of the image and it's kind of
       * lossy compression, but it is not as obvious as setting [quality]
       * to this Quality object.
       * If this is not allowed, than images will rendered using the best
       * quality, thus more memory space is taken. It's suggested to open
       * this setting
       * </pre>
       *
       * <code>bool autoDownscale = 1;</code>
       * @return The autoDownscale.
       */
      @java.lang.Override
      public boolean getAutoDownscale() {
        return autoDownscale_;
      }
      /**
       * <pre>
       * Allow the plugin the recalculate the image size along with
       * target device's density DPI, this logic is in utils/GeometryUtil.kt
       * This will result in resampling of the image and it's kind of
       * lossy compression, but it is not as obvious as setting [quality]
       * to this Quality object.
       * If this is not allowed, than images will rendered using the best
       * quality, thus more memory space is taken. It's suggested to open
       * this setting
       * </pre>
       *
       * <code>bool autoDownscale = 1;</code>
       * @param value The autoDownscale to set.
       * @return This builder for chaining.
       */
      public Builder setAutoDownscale(boolean value) {
        
        autoDownscale_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Allow the plugin the recalculate the image size along with
       * target device's density DPI, this logic is in utils/GeometryUtil.kt
       * This will result in resampling of the image and it's kind of
       * lossy compression, but it is not as obvious as setting [quality]
       * to this Quality object.
       * If this is not allowed, than images will rendered using the best
       * quality, thus more memory space is taken. It's suggested to open
       * this setting
       * </pre>
       *
       * <code>bool autoDownscale = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearAutoDownscale() {
        
        autoDownscale_ = false;
        onChanged();
        return this;
      }

      private int minimumAutoDownscaleTriggerSize_ ;
      /**
       * <pre>
       * If one of the image dimensions' value is lower than this value,
       * it will not downscale automatically although [autoDownscale] is
       * enabled to guarantee no over-reduced image quality. The this value
       * is not allow smaller than 80
       * </pre>
       *
       * <code>int32 minimumAutoDownscaleTriggerSize = 2;</code>
       * @return The minimumAutoDownscaleTriggerSize.
       */
      @java.lang.Override
      public int getMinimumAutoDownscaleTriggerSize() {
        return minimumAutoDownscaleTriggerSize_;
      }
      /**
       * <pre>
       * If one of the image dimensions' value is lower than this value,
       * it will not downscale automatically although [autoDownscale] is
       * enabled to guarantee no over-reduced image quality. The this value
       * is not allow smaller than 80
       * </pre>
       *
       * <code>int32 minimumAutoDownscaleTriggerSize = 2;</code>
       * @param value The minimumAutoDownscaleTriggerSize to set.
       * @return This builder for chaining.
       */
      public Builder setMinimumAutoDownscaleTriggerSize(int value) {
        
        minimumAutoDownscaleTriggerSize_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * If one of the image dimensions' value is lower than this value,
       * it will not downscale automatically although [autoDownscale] is
       * enabled to guarantee no over-reduced image quality. The this value
       * is not allow smaller than 80
       * </pre>
       *
       * <code>int32 minimumAutoDownscaleTriggerSize = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMinimumAutoDownscaleTriggerSize() {
        
        minimumAutoDownscaleTriggerSize_ = 0;
        onChanged();
        return this;
      }

      private int quality_ ;
      /**
       * <pre>
       * Image compression quality, assgining this value will trigger
       * compression logic of target bitmap, and it's lossy compression
       * if the target bitmap is not in PNG format. Comporess will
       * cost CPU time to save memory space, it's not suggested to do
       * compression if there's no memory pressure
       * </pre>
       *
       * <code>int32 quality = 3;</code>
       * @return The quality.
       */
      @java.lang.Override
      public int getQuality() {
        return quality_;
      }
      /**
       * <pre>
       * Image compression quality, assgining this value will trigger
       * compression logic of target bitmap, and it's lossy compression
       * if the target bitmap is not in PNG format. Comporess will
       * cost CPU time to save memory space, it's not suggested to do
       * compression if there's no memory pressure
       * </pre>
       *
       * <code>int32 quality = 3;</code>
       * @param value The quality to set.
       * @return This builder for chaining.
       */
      public Builder setQuality(int value) {
        
        quality_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Image compression quality, assgining this value will trigger
       * compression logic of target bitmap, and it's lossy compression
       * if the target bitmap is not in PNG format. Comporess will
       * cost CPU time to save memory space, it's not suggested to do
       * compression if there's no memory pressure
       * </pre>
       *
       * <code>int32 quality = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearQuality() {
        
        quality_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:Quality)
    }

    // @@protoc_insertion_point(class_scope:Quality)
    private static final com.texture_image.proto.ImageUtils.Quality DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.texture_image.proto.ImageUtils.Quality();
    }

    public static com.texture_image.proto.ImageUtils.Quality getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<Quality>
        PARSER = new com.google.protobuf.AbstractParser<Quality>() {
      @java.lang.Override
      public Quality parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Quality(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<Quality> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<Quality> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.texture_image.proto.ImageUtils.Quality getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_BorderRadius_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_BorderRadius_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Geometry_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Geometry_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_Quality_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_Quality_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\021image_utils.proto\"Z\n\014BorderRadius\022\017\n\007t" +
      "opLeft\030\001 \001(\001\022\020\n\010topRight\030\002 \001(\001\022\022\n\nbottom" +
      "Left\030\003 \001(\001\022\023\n\013bottomRight\030\004 \001(\001\"z\n\010Geome" +
      "try\022\r\n\005width\030\001 \001(\005\022\016\n\006height\030\002 \001(\005\022\024\n\014su" +
      "pportAlpha\030\003 \001(\010\022\024\n\003fit\030\004 \001(\0162\007.BoxFit\022#" +
      "\n\014borderRadius\030\005 \001(\0132\r.BorderRadius\"Z\n\007Q" +
      "uality\022\025\n\rautoDownscale\030\001 \001(\010\022\'\n\037minimum" +
      "AutoDownscaleTriggerSize\030\002 \001(\005\022\017\n\007qualit" +
      "y\030\003 \001(\005*G\n\006BoxFit\022\010\n\004fill\020\000\022\013\n\007contain\020\001" +
      "\022\t\n\005cover\020\002\022\014\n\010fitWidth\020\003\022\r\n\tfitHeight\020\004" +
      "*r\n\tTaskState\022\017\n\013initialized\020\000\022\013\n\007loadin" +
      "g\020\001\022\r\n\tcompleted\020\002\022\n\n\006failed\020\003\022\014\n\010dispos" +
      "ed\020\004\022\r\n\tundefined\020\005\022\017\n\013prepreReuse\020\006B\031\n\027" +
      "com.texture_image.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        });
    internal_static_BorderRadius_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_BorderRadius_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_BorderRadius_descriptor,
        new java.lang.String[] { "TopLeft", "TopRight", "BottomLeft", "BottomRight", });
    internal_static_Geometry_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_Geometry_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Geometry_descriptor,
        new java.lang.String[] { "Width", "Height", "SupportAlpha", "Fit", "BorderRadius", });
    internal_static_Quality_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_Quality_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_Quality_descriptor,
        new java.lang.String[] { "AutoDownscale", "MinimumAutoDownscaleTriggerSize", "Quality", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
