// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: image_info.proto

package com.texture_image.proto;

public final class ImageInfo {
  private ImageInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface TextureImageInfoOrBuilder extends
      // @@protoc_insertion_point(interface_extends:TextureImageInfo)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <code>int32 width = 2;</code>
     * @return The width.
     */
    int getWidth();

    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    int getHeight();

    /**
     * <code>string errorPlaceholder = 4;</code>
     * @return The errorPlaceholder.
     */
    java.lang.String getErrorPlaceholder();
    /**
     * <code>string errorPlaceholder = 4;</code>
     * @return The bytes for errorPlaceholder.
     */
    com.google.protobuf.ByteString
        getErrorPlaceholderBytes();

    /**
     * <code>string placeholder = 5;</code>
     * @return The placeholder.
     */
    java.lang.String getPlaceholder();
    /**
     * <code>string placeholder = 5;</code>
     * @return The bytes for placeholder.
     */
    com.google.protobuf.ByteString
        getPlaceholderBytes();

    /**
     * <code>.ImageBorderRadius borderRadius = 6;</code>
     * @return Whether the borderRadius field is set.
     */
    boolean hasBorderRadius();
    /**
     * <code>.ImageBorderRadius borderRadius = 6;</code>
     * @return The borderRadius.
     */
    com.texture_image.proto.BorderRadius.ImageBorderRadius getBorderRadius();
    /**
     * <code>.ImageBorderRadius borderRadius = 6;</code>
     */
    com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder getBorderRadiusOrBuilder();
  }
  /**
   * Protobuf type {@code TextureImageInfo}
   */
  public static final class TextureImageInfo extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:TextureImageInfo)
      TextureImageInfoOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use TextureImageInfo.newBuilder() to construct.
    private TextureImageInfo(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private TextureImageInfo() {
      url_ = "";
      errorPlaceholder_ = "";
      placeholder_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new TextureImageInfo();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private TextureImageInfo(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 10: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 16: {

              width_ = input.readInt32();
              break;
            }
            case 24: {

              height_ = input.readInt32();
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              errorPlaceholder_ = s;
              break;
            }
            case 42: {
              java.lang.String s = input.readStringRequireUtf8();

              placeholder_ = s;
              break;
            }
            case 50: {
              com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder subBuilder = null;
              if (borderRadius_ != null) {
                subBuilder = borderRadius_.toBuilder();
              }
              borderRadius_ = input.readMessage(com.texture_image.proto.BorderRadius.ImageBorderRadius.parser(), extensionRegistry);
              if (subBuilder != null) {
                subBuilder.mergeFrom(borderRadius_);
                borderRadius_ = subBuilder.buildPartial();
              }

              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.texture_image.proto.ImageInfo.internal_static_TextureImageInfo_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.texture_image.proto.ImageInfo.internal_static_TextureImageInfo_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.texture_image.proto.ImageInfo.TextureImageInfo.class, com.texture_image.proto.ImageInfo.TextureImageInfo.Builder.class);
    }

    public static final int URL_FIELD_NUMBER = 1;
    private volatile java.lang.Object url_;
    /**
     * <code>string url = 1;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <code>string url = 1;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int WIDTH_FIELD_NUMBER = 2;
    private int width_;
    /**
     * <code>int32 width = 2;</code>
     * @return The width.
     */
    @java.lang.Override
    public int getWidth() {
      return width_;
    }

    public static final int HEIGHT_FIELD_NUMBER = 3;
    private int height_;
    /**
     * <code>int32 height = 3;</code>
     * @return The height.
     */
    @java.lang.Override
    public int getHeight() {
      return height_;
    }

    public static final int ERRORPLACEHOLDER_FIELD_NUMBER = 4;
    private volatile java.lang.Object errorPlaceholder_;
    /**
     * <code>string errorPlaceholder = 4;</code>
     * @return The errorPlaceholder.
     */
    @java.lang.Override
    public java.lang.String getErrorPlaceholder() {
      java.lang.Object ref = errorPlaceholder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        errorPlaceholder_ = s;
        return s;
      }
    }
    /**
     * <code>string errorPlaceholder = 4;</code>
     * @return The bytes for errorPlaceholder.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getErrorPlaceholderBytes() {
      java.lang.Object ref = errorPlaceholder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        errorPlaceholder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int PLACEHOLDER_FIELD_NUMBER = 5;
    private volatile java.lang.Object placeholder_;
    /**
     * <code>string placeholder = 5;</code>
     * @return The placeholder.
     */
    @java.lang.Override
    public java.lang.String getPlaceholder() {
      java.lang.Object ref = placeholder_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        placeholder_ = s;
        return s;
      }
    }
    /**
     * <code>string placeholder = 5;</code>
     * @return The bytes for placeholder.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getPlaceholderBytes() {
      java.lang.Object ref = placeholder_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        placeholder_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int BORDERRADIUS_FIELD_NUMBER = 6;
    private com.texture_image.proto.BorderRadius.ImageBorderRadius borderRadius_;
    /**
     * <code>.ImageBorderRadius borderRadius = 6;</code>
     * @return Whether the borderRadius field is set.
     */
    @java.lang.Override
    public boolean hasBorderRadius() {
      return borderRadius_ != null;
    }
    /**
     * <code>.ImageBorderRadius borderRadius = 6;</code>
     * @return The borderRadius.
     */
    @java.lang.Override
    public com.texture_image.proto.BorderRadius.ImageBorderRadius getBorderRadius() {
      return borderRadius_ == null ? com.texture_image.proto.BorderRadius.ImageBorderRadius.getDefaultInstance() : borderRadius_;
    }
    /**
     * <code>.ImageBorderRadius borderRadius = 6;</code>
     */
    @java.lang.Override
    public com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder getBorderRadiusOrBuilder() {
      return getBorderRadius();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 1, url_);
      }
      if (width_ != 0) {
        output.writeInt32(2, width_);
      }
      if (height_ != 0) {
        output.writeInt32(3, height_);
      }
      if (!getErrorPlaceholderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, errorPlaceholder_);
      }
      if (!getPlaceholderBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 5, placeholder_);
      }
      if (borderRadius_ != null) {
        output.writeMessage(6, getBorderRadius());
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(1, url_);
      }
      if (width_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, width_);
      }
      if (height_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, height_);
      }
      if (!getErrorPlaceholderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, errorPlaceholder_);
      }
      if (!getPlaceholderBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(5, placeholder_);
      }
      if (borderRadius_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getBorderRadius());
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.texture_image.proto.ImageInfo.TextureImageInfo)) {
        return super.equals(obj);
      }
      com.texture_image.proto.ImageInfo.TextureImageInfo other = (com.texture_image.proto.ImageInfo.TextureImageInfo) obj;

      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (getWidth()
          != other.getWidth()) return false;
      if (getHeight()
          != other.getHeight()) return false;
      if (!getErrorPlaceholder()
          .equals(other.getErrorPlaceholder())) return false;
      if (!getPlaceholder()
          .equals(other.getPlaceholder())) return false;
      if (hasBorderRadius() != other.hasBorderRadius()) return false;
      if (hasBorderRadius()) {
        if (!getBorderRadius()
            .equals(other.getBorderRadius())) return false;
      }
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + WIDTH_FIELD_NUMBER;
      hash = (53 * hash) + getWidth();
      hash = (37 * hash) + HEIGHT_FIELD_NUMBER;
      hash = (53 * hash) + getHeight();
      hash = (37 * hash) + ERRORPLACEHOLDER_FIELD_NUMBER;
      hash = (53 * hash) + getErrorPlaceholder().hashCode();
      hash = (37 * hash) + PLACEHOLDER_FIELD_NUMBER;
      hash = (53 * hash) + getPlaceholder().hashCode();
      if (hasBorderRadius()) {
        hash = (37 * hash) + BORDERRADIUS_FIELD_NUMBER;
        hash = (53 * hash) + getBorderRadius().hashCode();
      }
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.ImageInfo.TextureImageInfo parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.texture_image.proto.ImageInfo.TextureImageInfo prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code TextureImageInfo}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:TextureImageInfo)
        com.texture_image.proto.ImageInfo.TextureImageInfoOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.texture_image.proto.ImageInfo.internal_static_TextureImageInfo_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.texture_image.proto.ImageInfo.internal_static_TextureImageInfo_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.texture_image.proto.ImageInfo.TextureImageInfo.class, com.texture_image.proto.ImageInfo.TextureImageInfo.Builder.class);
      }

      // Construct using com.texture_image.proto.ImageInfo.TextureImageInfo.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        url_ = "";

        width_ = 0;

        height_ = 0;

        errorPlaceholder_ = "";

        placeholder_ = "";

        if (borderRadiusBuilder_ == null) {
          borderRadius_ = null;
        } else {
          borderRadius_ = null;
          borderRadiusBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.texture_image.proto.ImageInfo.internal_static_TextureImageInfo_descriptor;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageInfo.TextureImageInfo getDefaultInstanceForType() {
        return com.texture_image.proto.ImageInfo.TextureImageInfo.getDefaultInstance();
      }

      @java.lang.Override
      public com.texture_image.proto.ImageInfo.TextureImageInfo build() {
        com.texture_image.proto.ImageInfo.TextureImageInfo result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.texture_image.proto.ImageInfo.TextureImageInfo buildPartial() {
        com.texture_image.proto.ImageInfo.TextureImageInfo result = new com.texture_image.proto.ImageInfo.TextureImageInfo(this);
        result.url_ = url_;
        result.width_ = width_;
        result.height_ = height_;
        result.errorPlaceholder_ = errorPlaceholder_;
        result.placeholder_ = placeholder_;
        if (borderRadiusBuilder_ == null) {
          result.borderRadius_ = borderRadius_;
        } else {
          result.borderRadius_ = borderRadiusBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.texture_image.proto.ImageInfo.TextureImageInfo) {
          return mergeFrom((com.texture_image.proto.ImageInfo.TextureImageInfo)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.texture_image.proto.ImageInfo.TextureImageInfo other) {
        if (other == com.texture_image.proto.ImageInfo.TextureImageInfo.getDefaultInstance()) return this;
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.getWidth() != 0) {
          setWidth(other.getWidth());
        }
        if (other.getHeight() != 0) {
          setHeight(other.getHeight());
        }
        if (!other.getErrorPlaceholder().isEmpty()) {
          errorPlaceholder_ = other.errorPlaceholder_;
          onChanged();
        }
        if (!other.getPlaceholder().isEmpty()) {
          placeholder_ = other.placeholder_;
          onChanged();
        }
        if (other.hasBorderRadius()) {
          mergeBorderRadius(other.getBorderRadius());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.texture_image.proto.ImageInfo.TextureImageInfo parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.texture_image.proto.ImageInfo.TextureImageInfo) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <code>string url = 1;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string url = 1;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <code>string url = 1;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int width_ ;
      /**
       * <code>int32 width = 2;</code>
       * @return The width.
       */
      @java.lang.Override
      public int getWidth() {
        return width_;
      }
      /**
       * <code>int32 width = 2;</code>
       * @param value The width to set.
       * @return This builder for chaining.
       */
      public Builder setWidth(int value) {
        
        width_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 width = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearWidth() {
        
        width_ = 0;
        onChanged();
        return this;
      }

      private int height_ ;
      /**
       * <code>int32 height = 3;</code>
       * @return The height.
       */
      @java.lang.Override
      public int getHeight() {
        return height_;
      }
      /**
       * <code>int32 height = 3;</code>
       * @param value The height to set.
       * @return This builder for chaining.
       */
      public Builder setHeight(int value) {
        
        height_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 height = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearHeight() {
        
        height_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object errorPlaceholder_ = "";
      /**
       * <code>string errorPlaceholder = 4;</code>
       * @return The errorPlaceholder.
       */
      public java.lang.String getErrorPlaceholder() {
        java.lang.Object ref = errorPlaceholder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          errorPlaceholder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string errorPlaceholder = 4;</code>
       * @return The bytes for errorPlaceholder.
       */
      public com.google.protobuf.ByteString
          getErrorPlaceholderBytes() {
        java.lang.Object ref = errorPlaceholder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          errorPlaceholder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string errorPlaceholder = 4;</code>
       * @param value The errorPlaceholder to set.
       * @return This builder for chaining.
       */
      public Builder setErrorPlaceholder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        errorPlaceholder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string errorPlaceholder = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearErrorPlaceholder() {
        
        errorPlaceholder_ = getDefaultInstance().getErrorPlaceholder();
        onChanged();
        return this;
      }
      /**
       * <code>string errorPlaceholder = 4;</code>
       * @param value The bytes for errorPlaceholder to set.
       * @return This builder for chaining.
       */
      public Builder setErrorPlaceholderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        errorPlaceholder_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object placeholder_ = "";
      /**
       * <code>string placeholder = 5;</code>
       * @return The placeholder.
       */
      public java.lang.String getPlaceholder() {
        java.lang.Object ref = placeholder_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          placeholder_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string placeholder = 5;</code>
       * @return The bytes for placeholder.
       */
      public com.google.protobuf.ByteString
          getPlaceholderBytes() {
        java.lang.Object ref = placeholder_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          placeholder_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string placeholder = 5;</code>
       * @param value The placeholder to set.
       * @return This builder for chaining.
       */
      public Builder setPlaceholder(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        placeholder_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string placeholder = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearPlaceholder() {
        
        placeholder_ = getDefaultInstance().getPlaceholder();
        onChanged();
        return this;
      }
      /**
       * <code>string placeholder = 5;</code>
       * @param value The bytes for placeholder to set.
       * @return This builder for chaining.
       */
      public Builder setPlaceholderBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        placeholder_ = value;
        onChanged();
        return this;
      }

      private com.texture_image.proto.BorderRadius.ImageBorderRadius borderRadius_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.texture_image.proto.BorderRadius.ImageBorderRadius, com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder, com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder> borderRadiusBuilder_;
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       * @return Whether the borderRadius field is set.
       */
      public boolean hasBorderRadius() {
        return borderRadiusBuilder_ != null || borderRadius_ != null;
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       * @return The borderRadius.
       */
      public com.texture_image.proto.BorderRadius.ImageBorderRadius getBorderRadius() {
        if (borderRadiusBuilder_ == null) {
          return borderRadius_ == null ? com.texture_image.proto.BorderRadius.ImageBorderRadius.getDefaultInstance() : borderRadius_;
        } else {
          return borderRadiusBuilder_.getMessage();
        }
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      public Builder setBorderRadius(com.texture_image.proto.BorderRadius.ImageBorderRadius value) {
        if (borderRadiusBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          borderRadius_ = value;
          onChanged();
        } else {
          borderRadiusBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      public Builder setBorderRadius(
          com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder builderForValue) {
        if (borderRadiusBuilder_ == null) {
          borderRadius_ = builderForValue.build();
          onChanged();
        } else {
          borderRadiusBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      public Builder mergeBorderRadius(com.texture_image.proto.BorderRadius.ImageBorderRadius value) {
        if (borderRadiusBuilder_ == null) {
          if (borderRadius_ != null) {
            borderRadius_ =
              com.texture_image.proto.BorderRadius.ImageBorderRadius.newBuilder(borderRadius_).mergeFrom(value).buildPartial();
          } else {
            borderRadius_ = value;
          }
          onChanged();
        } else {
          borderRadiusBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      public Builder clearBorderRadius() {
        if (borderRadiusBuilder_ == null) {
          borderRadius_ = null;
          onChanged();
        } else {
          borderRadius_ = null;
          borderRadiusBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      public com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder getBorderRadiusBuilder() {
        
        onChanged();
        return getBorderRadiusFieldBuilder().getBuilder();
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      public com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder getBorderRadiusOrBuilder() {
        if (borderRadiusBuilder_ != null) {
          return borderRadiusBuilder_.getMessageOrBuilder();
        } else {
          return borderRadius_ == null ?
              com.texture_image.proto.BorderRadius.ImageBorderRadius.getDefaultInstance() : borderRadius_;
        }
      }
      /**
       * <code>.ImageBorderRadius borderRadius = 6;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.texture_image.proto.BorderRadius.ImageBorderRadius, com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder, com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder> 
          getBorderRadiusFieldBuilder() {
        if (borderRadiusBuilder_ == null) {
          borderRadiusBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.texture_image.proto.BorderRadius.ImageBorderRadius, com.texture_image.proto.BorderRadius.ImageBorderRadius.Builder, com.texture_image.proto.BorderRadius.ImageBorderRadiusOrBuilder>(
                  getBorderRadius(),
                  getParentForChildren(),
                  isClean());
          borderRadius_ = null;
        }
        return borderRadiusBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:TextureImageInfo)
    }

    // @@protoc_insertion_point(class_scope:TextureImageInfo)
    private static final com.texture_image.proto.ImageInfo.TextureImageInfo DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.texture_image.proto.ImageInfo.TextureImageInfo();
    }

    public static com.texture_image.proto.ImageInfo.TextureImageInfo getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<TextureImageInfo>
        PARSER = new com.google.protobuf.AbstractParser<TextureImageInfo>() {
      @java.lang.Override
      public TextureImageInfo parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new TextureImageInfo(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<TextureImageInfo> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<TextureImageInfo> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.texture_image.proto.ImageInfo.TextureImageInfo getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_TextureImageInfo_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_TextureImageInfo_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020image_info.proto\032\023border_radius.proto\"" +
      "\227\001\n\020TextureImageInfo\022\013\n\003url\030\001 \001(\t\022\r\n\005wid" +
      "th\030\002 \001(\005\022\016\n\006height\030\003 \001(\005\022\030\n\020errorPlaceho" +
      "lder\030\004 \001(\t\022\023\n\013placeholder\030\005 \001(\t\022(\n\014borde" +
      "rRadius\030\006 \001(\0132\022.ImageBorderRadiusB\031\n\027com" +
      ".texture_image.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.texture_image.proto.BorderRadius.getDescriptor(),
        });
    internal_static_TextureImageInfo_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_TextureImageInfo_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_TextureImageInfo_descriptor,
        new java.lang.String[] { "Url", "Width", "Height", "ErrorPlaceholder", "Placeholder", "BorderRadius", });
    com.texture_image.proto.BorderRadius.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
