// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: method_call_result.proto

package com.texture_image.proto;

public final class MethodCallResult {
  private MethodCallResult() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  public interface ImageResultOrBuilder extends
      // @@protoc_insertion_point(interface_extends:ImageResult)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <pre>
     * The result code of process, if this code's value is not 200
     * then the [textureId] shall be invalid and error placeholder
     * is supposed to be shown on this situation
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <pre>
     * Relative underlay Texture id for this image
     * </pre>
     *
     * <code>int64 textureId = 2;</code>
     * @return The textureId.
     */
    long getTextureId();

    /**
     * <pre>
     * Description for the result
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <pre>
     * Description for the result
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <pre>
     * Image url
     * </pre>
     *
     * <code>string url = 4;</code>
     * @return The url.
     */
    java.lang.String getUrl();
    /**
     * <pre>
     * Image url
     * </pre>
     *
     * <code>string url = 4;</code>
     * @return The bytes for url.
     */
    com.google.protobuf.ByteString
        getUrlBytes();

    /**
     * <pre>
     * Relative image fetching task's current status
     * </pre>
     *
     * <code>.ImageTaskState state = 5;</code>
     * @return The enum numeric value on the wire for state.
     */
    int getStateValue();
    /**
     * <pre>
     * Relative image fetching task's current status
     * </pre>
     *
     * <code>.ImageTaskState state = 5;</code>
     * @return The state.
     */
    com.texture_image.proto.Enum.ImageTaskState getState();
  }
  /**
   * <pre>
   * An object to describe image request API invoking result
   * Flutter side may use the [textureId] to rebuild its UI
   * when receiving the result, but the target image may not
   * be shown right away because it maybe downloading by now
   * you can check [state] for the relative task's newest status
   * </pre>
   *
   * Protobuf type {@code ImageResult}
   */
  public static final class ImageResult extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:ImageResult)
      ImageResultOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use ImageResult.newBuilder() to construct.
    private ImageResult(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private ImageResult() {
      message_ = "";
      url_ = "";
      state_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new ImageResult();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    private ImageResult(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      this();
      if (extensionRegistry == null) {
        throw new java.lang.NullPointerException();
      }
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            case 8: {

              code_ = input.readInt32();
              break;
            }
            case 16: {

              textureId_ = input.readInt64();
              break;
            }
            case 26: {
              java.lang.String s = input.readStringRequireUtf8();

              message_ = s;
              break;
            }
            case 34: {
              java.lang.String s = input.readStringRequireUtf8();

              url_ = s;
              break;
            }
            case 40: {
              int rawValue = input.readEnum();

              state_ = rawValue;
              break;
            }
            default: {
              if (!parseUnknownField(
                  input, unknownFields, extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.texture_image.proto.MethodCallResult.internal_static_ImageResult_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.texture_image.proto.MethodCallResult.internal_static_ImageResult_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.texture_image.proto.MethodCallResult.ImageResult.class, com.texture_image.proto.MethodCallResult.ImageResult.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 1;
    private int code_;
    /**
     * <pre>
     * The result code of process, if this code's value is not 200
     * then the [textureId] shall be invalid and error placeholder
     * is supposed to be shown on this situation
     * </pre>
     *
     * <code>int32 code = 1;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int TEXTUREID_FIELD_NUMBER = 2;
    private long textureId_;
    /**
     * <pre>
     * Relative underlay Texture id for this image
     * </pre>
     *
     * <code>int64 textureId = 2;</code>
     * @return The textureId.
     */
    @java.lang.Override
    public long getTextureId() {
      return textureId_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <pre>
     * Description for the result
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Description for the result
     * </pre>
     *
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int URL_FIELD_NUMBER = 4;
    private volatile java.lang.Object url_;
    /**
     * <pre>
     * Image url
     * </pre>
     *
     * <code>string url = 4;</code>
     * @return The url.
     */
    @java.lang.Override
    public java.lang.String getUrl() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        url_ = s;
        return s;
      }
    }
    /**
     * <pre>
     * Image url
     * </pre>
     *
     * <code>string url = 4;</code>
     * @return The bytes for url.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getUrlBytes() {
      java.lang.Object ref = url_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        url_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    public static final int STATE_FIELD_NUMBER = 5;
    private int state_;
    /**
     * <pre>
     * Relative image fetching task's current status
     * </pre>
     *
     * <code>.ImageTaskState state = 5;</code>
     * @return The enum numeric value on the wire for state.
     */
    @java.lang.Override public int getStateValue() {
      return state_;
    }
    /**
     * <pre>
     * Relative image fetching task's current status
     * </pre>
     *
     * <code>.ImageTaskState state = 5;</code>
     * @return The state.
     */
    @java.lang.Override public com.texture_image.proto.Enum.ImageTaskState getState() {
      @SuppressWarnings("deprecation")
      com.texture_image.proto.Enum.ImageTaskState result = com.texture_image.proto.Enum.ImageTaskState.valueOf(state_);
      return result == null ? com.texture_image.proto.Enum.ImageTaskState.UNRECOGNIZED : result;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(1, code_);
      }
      if (textureId_ != 0L) {
        output.writeInt64(2, textureId_);
      }
      if (!getMessageBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      if (!getUrlBytes().isEmpty()) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 4, url_);
      }
      if (state_ != com.texture_image.proto.Enum.ImageTaskState.initialized.getNumber()) {
        output.writeEnum(5, state_);
      }
      unknownFields.writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, code_);
      }
      if (textureId_ != 0L) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, textureId_);
      }
      if (!getMessageBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      if (!getUrlBytes().isEmpty()) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(4, url_);
      }
      if (state_ != com.texture_image.proto.Enum.ImageTaskState.initialized.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(5, state_);
      }
      size += unknownFields.getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof com.texture_image.proto.MethodCallResult.ImageResult)) {
        return super.equals(obj);
      }
      com.texture_image.proto.MethodCallResult.ImageResult other = (com.texture_image.proto.MethodCallResult.ImageResult) obj;

      if (getCode()
          != other.getCode()) return false;
      if (getTextureId()
          != other.getTextureId()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUrl()
          .equals(other.getUrl())) return false;
      if (state_ != other.state_) return false;
      if (!unknownFields.equals(other.unknownFields)) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + TEXTUREID_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashLong(
          getTextureId());
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (37 * hash) + URL_FIELD_NUMBER;
      hash = (53 * hash) + getUrl().hashCode();
      hash = (37 * hash) + STATE_FIELD_NUMBER;
      hash = (53 * hash) + state_;
      hash = (29 * hash) + unknownFields.hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static com.texture_image.proto.MethodCallResult.ImageResult parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(com.texture_image.proto.MethodCallResult.ImageResult prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * An object to describe image request API invoking result
     * Flutter side may use the [textureId] to rebuild its UI
     * when receiving the result, but the target image may not
     * be shown right away because it maybe downloading by now
     * you can check [state] for the relative task's newest status
     * </pre>
     *
     * Protobuf type {@code ImageResult}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:ImageResult)
        com.texture_image.proto.MethodCallResult.ImageResultOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.texture_image.proto.MethodCallResult.internal_static_ImageResult_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.texture_image.proto.MethodCallResult.internal_static_ImageResult_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.texture_image.proto.MethodCallResult.ImageResult.class, com.texture_image.proto.MethodCallResult.ImageResult.Builder.class);
      }

      // Construct using com.texture_image.proto.MethodCallResult.ImageResult.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessageV3
                .alwaysUseFieldBuilders) {
        }
      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        textureId_ = 0L;

        message_ = "";

        url_ = "";

        state_ = 0;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.texture_image.proto.MethodCallResult.internal_static_ImageResult_descriptor;
      }

      @java.lang.Override
      public com.texture_image.proto.MethodCallResult.ImageResult getDefaultInstanceForType() {
        return com.texture_image.proto.MethodCallResult.ImageResult.getDefaultInstance();
      }

      @java.lang.Override
      public com.texture_image.proto.MethodCallResult.ImageResult build() {
        com.texture_image.proto.MethodCallResult.ImageResult result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public com.texture_image.proto.MethodCallResult.ImageResult buildPartial() {
        com.texture_image.proto.MethodCallResult.ImageResult result = new com.texture_image.proto.MethodCallResult.ImageResult(this);
        result.code_ = code_;
        result.textureId_ = textureId_;
        result.message_ = message_;
        result.url_ = url_;
        result.state_ = state_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.texture_image.proto.MethodCallResult.ImageResult) {
          return mergeFrom((com.texture_image.proto.MethodCallResult.ImageResult)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.texture_image.proto.MethodCallResult.ImageResult other) {
        if (other == com.texture_image.proto.MethodCallResult.ImageResult.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (other.getTextureId() != 0L) {
          setTextureId(other.getTextureId());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        if (!other.getUrl().isEmpty()) {
          url_ = other.url_;
          onChanged();
        }
        if (other.state_ != 0) {
          setStateValue(other.getStateValue());
        }
        this.mergeUnknownFields(other.unknownFields);
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.texture_image.proto.MethodCallResult.ImageResult parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.texture_image.proto.MethodCallResult.ImageResult) e.getUnfinishedMessage();
          throw e.unwrapIOException();
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }

      private int code_ ;
      /**
       * <pre>
       * The result code of process, if this code's value is not 200
       * then the [textureId] shall be invalid and error placeholder
       * is supposed to be shown on this situation
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <pre>
       * The result code of process, if this code's value is not 200
       * then the [textureId] shall be invalid and error placeholder
       * is supposed to be shown on this situation
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * The result code of process, if this code's value is not 200
       * then the [textureId] shall be invalid and error placeholder
       * is supposed to be shown on this situation
       * </pre>
       *
       * <code>int32 code = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private long textureId_ ;
      /**
       * <pre>
       * Relative underlay Texture id for this image
       * </pre>
       *
       * <code>int64 textureId = 2;</code>
       * @return The textureId.
       */
      @java.lang.Override
      public long getTextureId() {
        return textureId_;
      }
      /**
       * <pre>
       * Relative underlay Texture id for this image
       * </pre>
       *
       * <code>int64 textureId = 2;</code>
       * @param value The textureId to set.
       * @return This builder for chaining.
       */
      public Builder setTextureId(long value) {
        
        textureId_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Relative underlay Texture id for this image
       * </pre>
       *
       * <code>int64 textureId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearTextureId() {
        
        textureId_ = 0L;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <pre>
       * Description for the result
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Description for the result
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Description for the result
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Description for the result
       * </pre>
       *
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Description for the result
       * </pre>
       *
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }

      private java.lang.Object url_ = "";
      /**
       * <pre>
       * Image url
       * </pre>
       *
       * <code>string url = 4;</code>
       * @return The url.
       */
      public java.lang.String getUrl() {
        java.lang.Object ref = url_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          url_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <pre>
       * Image url
       * </pre>
       *
       * <code>string url = 4;</code>
       * @return The bytes for url.
       */
      public com.google.protobuf.ByteString
          getUrlBytes() {
        java.lang.Object ref = url_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          url_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <pre>
       * Image url
       * </pre>
       *
       * <code>string url = 4;</code>
       * @param value The url to set.
       * @return This builder for chaining.
       */
      public Builder setUrl(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        url_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Image url
       * </pre>
       *
       * <code>string url = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearUrl() {
        
        url_ = getDefaultInstance().getUrl();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Image url
       * </pre>
       *
       * <code>string url = 4;</code>
       * @param value The bytes for url to set.
       * @return This builder for chaining.
       */
      public Builder setUrlBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        url_ = value;
        onChanged();
        return this;
      }

      private int state_ = 0;
      /**
       * <pre>
       * Relative image fetching task's current status
       * </pre>
       *
       * <code>.ImageTaskState state = 5;</code>
       * @return The enum numeric value on the wire for state.
       */
      @java.lang.Override public int getStateValue() {
        return state_;
      }
      /**
       * <pre>
       * Relative image fetching task's current status
       * </pre>
       *
       * <code>.ImageTaskState state = 5;</code>
       * @param value The enum numeric value on the wire for state to set.
       * @return This builder for chaining.
       */
      public Builder setStateValue(int value) {
        
        state_ = value;
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Relative image fetching task's current status
       * </pre>
       *
       * <code>.ImageTaskState state = 5;</code>
       * @return The state.
       */
      @java.lang.Override
      public com.texture_image.proto.Enum.ImageTaskState getState() {
        @SuppressWarnings("deprecation")
        com.texture_image.proto.Enum.ImageTaskState result = com.texture_image.proto.Enum.ImageTaskState.valueOf(state_);
        return result == null ? com.texture_image.proto.Enum.ImageTaskState.UNRECOGNIZED : result;
      }
      /**
       * <pre>
       * Relative image fetching task's current status
       * </pre>
       *
       * <code>.ImageTaskState state = 5;</code>
       * @param value The state to set.
       * @return This builder for chaining.
       */
      public Builder setState(com.texture_image.proto.Enum.ImageTaskState value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        state_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <pre>
       * Relative image fetching task's current status
       * </pre>
       *
       * <code>.ImageTaskState state = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearState() {
        
        state_ = 0;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:ImageResult)
    }

    // @@protoc_insertion_point(class_scope:ImageResult)
    private static final com.texture_image.proto.MethodCallResult.ImageResult DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new com.texture_image.proto.MethodCallResult.ImageResult();
    }

    public static com.texture_image.proto.MethodCallResult.ImageResult getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<ImageResult>
        PARSER = new com.google.protobuf.AbstractParser<ImageResult>() {
      @java.lang.Override
      public ImageResult parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new ImageResult(input, extensionRegistry);
      }
    };

    public static com.google.protobuf.Parser<ImageResult> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<ImageResult> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public com.texture_image.proto.MethodCallResult.ImageResult getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_ImageResult_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_ImageResult_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\030method_call_result.proto\032\nenum.proto\"l" +
      "\n\013ImageResult\022\014\n\004code\030\001 \001(\005\022\021\n\ttextureId" +
      "\030\002 \001(\003\022\017\n\007message\030\003 \001(\t\022\013\n\003url\030\004 \001(\t\022\036\n\005" +
      "state\030\005 \001(\0162\017.ImageTaskStateB\031\n\027com.text" +
      "ure_image.protob\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.texture_image.proto.Enum.getDescriptor(),
        });
    internal_static_ImageResult_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_ImageResult_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_ImageResult_descriptor,
        new java.lang.String[] { "Code", "TextureId", "Message", "Url", "State", });
    com.texture_image.proto.Enum.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
