/// Plugin API list
///
/// This file is generated by shell script on 2021-09-01, please don't edit this file manually

#import <Foundation/Foundation.h>

// Create a new texture image base on a [ImageFetchInfo]
extern NSString *const createImageTexture;

// Release or cache resource of a texture image once the widget nis disposed, param is of [ImageFetchCancelInfo] type
extern NSString *const disposeImageTexture;

// Sets the global config of the plugin, the config detail please refer to [ImageConfigInfo]
extern NSString *const textureImageConfig;

// Release all texures waiting in the to-be-reused queue, has no effect on those occupied by Flutter widgets
extern NSString *const releaseImageTextureCaches;

// Enable/disable console log, param is a boolean
extern NSString *const enableLog;

