/// Plugin API list
///
/// This file is generated by shell script on 2021-08-03, please don't edit this file manually

#import <Foundation/Foundation.h>

// Create a new texture image base on a [ImageFetchInfo]
extern NSString *const createImageTexture;

// Release resource of a texture image once the widget i disposed, param is of [ImageFetchCancelInfo] type
extern NSString *const destroyImageTexture;

// Sets the global config of the plugin, the config detail please refer to [ImageConfigInfo]
extern NSString *const textureImageConfig;

// Enable/disable console log, param is a boolean
extern NSString *const enableLog;

